# Generated by Django 4.2.7 on 2023-11-27 22:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_prescription_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
